# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImage)

    steps:
    - task: UseDotNet@2
      displayName: install .net 6
      inputs:
       packageType: sdk
       version: 6.x


    - task: NuGetToolInstaller@1
      displayName: nuget installer


    - task: NuGetCommand@2
      displayName: nuget restore
      inputs:
         restoreSolution: $(solution)

    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
       command: build
       projects: '**/*.csproj'
       arguments: '--configuration $(BuildConfiguration)'


    - task: DotNetCoreCLI@2
      displayName: dotnet publish
      inputs:
         arguments: '--configuration $(BuildConfiguration) --output $(build.Artifactstagingdirectory)'
         command: publish
         publishWebProjects: true
         zipAfterPublish: true


    - task: PublishBuildArtifacts@1
      displayName: publish artifact
      inputs:
         ArtifactName: 'webapp'
         PathtoPublish: $(build.Artifactstagingdirectory)


- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool: 
     vmImage: $(vmImage)

    steps:
      - download: 'current'
        artifact: 'webapp'
        displayName: webapp artifact download

      - script: ls -R $(System.DefaultWorkingDirectory)
        displayName: listing files


