apiVersion: v1
kind: Service
metadata:
  name: webapp8080
spec:
  type: LoadBalancer
  selector:
    app: webapp8080
  ports: 
   - protocol: TCP 
     port: 80
     targetPort: 8080
     name: http-webapp8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp8080
spec:  
  replicas: 2
  selector:
    matchLabels:
      app: webapp8080
  template:
    metadata:
      labels:
        app: webapp8080
    spec:
      containers:
      - name: webapp80
        image: testsureshacr.azurecr.io/webapp:8080
        ports:
        - containerPort: 8080