apiVersion: v1
kind: Service
metadata:
  name: webapp80
spec:
  type: LoadBalancer
  selector:
    app: webapp80
  ports: 
   - protocol: TCP 
     port: 80
     targetPort: 80
     name: http-webapp80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp80
spec:  
  replicas: 2
  selector:
    matchLabels:
      app: webapp80
  template:
    metadata:
      labels:
        app: webapp80
    spec:
      containers:
      - name: webapp80
        image: testsureshacr.azurecr.io/webapplication:146
        ports:
        - containerPort: 80