apiVersion: v1
kind: Service
metadata:
  name: webapp8081
spec:
  type: LoadBalancer
  selector:
    app: webapp8081
  ports: 
   - protocol: TCP 
     port: 80
     targetPort: 80
     name: http-webapp8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp8081
spec:  
  replicas: 2
  selector:
    matchLabels:
      app: webapp8081
  template:
    metadata:
      labels:
        app: webapp8081
    spec:
      containers:
      - name: webapp8081
        image: testsureshacr.azurecr.io/(imageRepository):$(tag)
        ports:
        - containerPort: 80