name: Build and Publish .NET Core Artifact

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore packages
      run: dotnet restore WebApp.sln

    - name: Build project
      run: dotnet build WebApp/WebApp.csproj --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish WebApp/WebApp.csproj --configuration Release --output ./output --no-build

    - name: Upload published artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-artifact
        path: ./output
  deploy:
   permissions:
    contents: write
    pages: write
    id-token: write
   environment:
    name: production
    url: ${{ steps.deployment.outputs.page_url }}
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Install .NET SDK
     uses: actions/setup-dotnet@v4
     with:
       dotnet-version: '8.0.x'

   - name: Restore packages
     run: dotnet restore WebApp.sln

   - name: Build project
     run: dotnet build WebApp/WebApp.csproj --configuration Release --no-restore

   - name: Publish project
     run: dotnet publish WebApp/WebApp.csproj --configuration Release --output ./output --no-build

   - name: Azure Login via OIDC
     uses: azure/login@v1
     with:
        client-id: 710b93b9-2fb7-4921-b45d-10fe45488c4d
        tenant-id: d52325e9-0810-46ae-89ca-93a81ab43fb7
        subscription-id: 082a5822-b215-41a0-919f-0527e9956494
        
   - name: Deploy to Azure Web App
     uses: azure/webapps-deploy@v2
     with:
        app-name: suretestapp
        package: ./output
