name: dot net package
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v4

    - name: dotnet setup
      uses: actions/dotnet-setup@v4
      with:
       dotnet-version: '3.1.x'

    - name: display dotnet version
      run: dotnet --version
