name: dot net package
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v4

    - name: dotnet setup
      uses: actions/setup-dotnet@v4
      with:
       dotnet-version: '6.x'

    - name: display dotnet version
      run: dotnet --version

    - name: Install dependencies
      run: dotnet restore
   
    - name: dotnet build
      run: dotnet build

    - name: Upload dotnet build results
      uses: actions/upload-artifact@v4
      with:
        path: /home/runner/work/webapp/
